mydata <- read.table("household_power_consumption.txt", header = T, sep = ';')
mydata$Date <- as.Date(mydata$Date, "%d/%m/%Y")
subsetdata <- subset(mydata, mydata$Date >= as.Date("2007-02-01", "%Y-%m-%d") & mydata$Date <= as.Date("2007-02-02", "%Y-%m-%d"))
subsetdata$Datetime <- strptime(paste(subsetdata$Date, subsetdata$Time, sep=" "), format="%Y-%m-%d %T")
subsetdata$Sub_metering_1 <- as.numeric(subsetdata$Sub_metering_1)
subsetdata$Sub_metering_2 <- as.numeric(subsetdata$Sub_metering_2)
subsetdata$Sub_metering_3 <- as.numeric(subsetdata$Sub_metering_3)
png(filename ="plot3.png")
plot(subsetdata$Datetime, subsetdata$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering", ylim=c(0,38))
lines(subsetdata$Datetime, subsetdata$Sub_metering_3, col="blue")
lines(subsetdata$Datetime[subsetdata$Sub_metering_2 <5], subsetdata$Sub_metering_2[subsetdata$Sub_metering_2 <5]-2, col="red")
lines(subsetdata$Datetime[subsetdata$Sub_metering_1 >20|subsetdata$Sub_metering_1 <10], subsetdata$Sub_metering_1[subsetdata$Sub_metering_1 >20|subsetdata$Sub_metering_1 <10]-2, col="black")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c("solid", "solid", "solid"))
dev.off()

