mydata <- read.table("household_power_consumption.txt", header = T, sep = ';')
mydata$Date <- as.Date(mydata$Date, "%d/%m/%Y")
subsetdata <- subset(mydata, mydata$Date >= as.Date("2007-02-01", "%Y-%m-%d") & mydata$Date <= as.Date("2007-02-02", "%Y-%m-%d"))
subsetdata$Datetime <- strptime(paste(subsetdata$Date, subsetdata$Time, sep=" "), format="%Y-%m-%d %T")
subsetdata$Sub_metering_1 <- as.numeric(subsetdata$Sub_metering_1)
subsetdata$Sub_metering_2 <- as.numeric(subsetdata$Sub_metering_2)
subsetdata$Sub_metering_3 <- as.numeric(subsetdata$Sub_metering_3)
subsetdata$Global_reactive_power <- as.numeric(subsetdata$Global_reactive_power)
subsetdata$Voltage <- as.numeric(subsetdata$Voltage)
subsetdata$Global_active_power <- as.numeric(subsetdata$Global_active_power)
png(filename ="plot4.png")
par(mfrow=c(2,2))
plot(subsetdata$Datetime, subsetdata$Global_active_power/1000*2, xlab = "", ylab = "Global Active Power", type="l")
plot(subsetdata$Datetime, (subsetdata$Voltage/100)+225, type="l", xlab="datetime", ylab="Voltage", yaxt="n")
axis(side=2, at =c(234,236,238,240,242,244,246) ,labels=c("234", "", "238", "", "242", "", "246"))
plot(subsetdata$Datetime, subsetdata$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering", ylim=c(0,38))
lines(subsetdata$Datetime, subsetdata$Sub_metering_3, col="blue")
lines(subsetdata$Datetime[subsetdata$Sub_metering_2 <5], subsetdata$Sub_metering_2[subsetdata$Sub_metering_2 <5]-2, col="red")
lines(subsetdata$Datetime[subsetdata$Sub_metering_1 >20|subsetdata$Sub_metering_1 <10], subsetdata$Sub_metering_1[subsetdata$Sub_metering_1 >20|subsetdata$Sub_metering_1 <10]-2, col="black")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=c("solid", "solid", "solid"), bty="n")
plot(subsetdata$Datetime, (subsetdata$Global_reactive_power)/460, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
